version: 2

sphinx:
    configuration: docs/conf.py
    fail_on_warning: false

formats: all

python:
   version: 3.6
   system_packages: true
   install:
       - requirements: requirements/core.txt
